### ISSUE TITLE
ASAN: High debug levels trigger stack-use-after-scope

### ISSUE THREAD

**Issue by kozdra** [verilator/verilator#3574]
I have built Verilator with AddressSanitizer enabled, and encountered a bug as follows:

```cpp
==227500==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd6eaa0b50 at pc 0x0000004bec58 bp 0x7ffd6eaa0460 sp 0x7ffd6eaa0458
READ of size 8 at 0x7ffd6eaa0b50 thread T0
    #0 0x4bec57 in AstNode::dumpPtrs(std::ostream&) const ../V3Ast.cpp:1112
    #1 0x4bf5a1 in AstNode::dumpTree(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const ../V3Ast.cpp:1122
    #2 0x4bf21e in AstNode::dumpTree(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const ../V3Ast.cpp:1132
    #3 0x4bf170 in AstNode::dumpTree(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const ../V3Ast.cpp:1129
    #4 0x4c637f in AstNode::dumpTreeFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) ../V3Ast.cpp:1163
    #5 0xa8319e in V3Global::dumpCheckGlobalTree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool) ../V3Global.cpp:96
    #6 0xc4dc32 in V3LinkLevel::modSortByLevel() ../V3LinkLevel.cpp:81
    #7 0x441d86 in process ../Verilator.cpp:117                                                                                                               
    #8 0x441d86 in verilate ../Verilator.cpp:606                                                                                                              
    #9 0x441d86 in main ../Verilator.cpp:732     
    #10 0x7efe102dad09 in __libc_start_main ../csu/libc-start.c:308
    #11 0x44c2d9 in _start (/home/ant/src/verilator-1/bin/verilator_bin+0x44c2d9)
```

The relevant source code reads:
```cpp
    if (m_iterpp) {                              // 1110
        os << " iterpp=" << cvtToHex(m_iterpp);  // 1111
        os << "*=" << cvtToHex(*m_iterpp);       // 1112
    }                                            // 1113
```

I guess that the code here might be the cause (since niterp is a local scoped variable), but I am not sure of how it could be fixed, because it looks correct to me:
```cpp
        niterp->m_iterpp = &niterp;
        niterp->accept(v);
        // accept may do a replaceNode and change niterp on us...
        // niterp maybe nullptr, so need cast if printing
        // if (niterp != nodep) UINFO(1,"iterateAndNext edited "<<cvtToHex(nodep)
        //                             <<" now into "<<cvtToHex(niterp)<<endl);
        if (!niterp) return;  // Perhaps node deleted inside accept
        niterp->m_iterpp = nullptr;
```

Steps to reproduce (the test chosen is not much relevant, it happens with almost every testcase):
```sh
export CFLAGS=-fsanitize=address CXXFLAGS=-fsanitize=address LDFLAGS=-fsanitize=address
autoconf
./configure
make -j`nproc`
test_regress/t/t_interface_inl.pl --debugi 9
```
You can also set `ASAN_OPTIONS=color=always` to get a colourful output.

I believe it did not crash without ASAN, because all the erroneous code does is read a no-longer-valid address, and print it, without dereferencing.  It is nevertheless limiting, because in order to use ASAN to debug my contributions to Verilator, I needed to restrict the debug level to 8, so I could not see the intermediate trees while using ASAN.

**Comment by wsnyder** [comment]
The problem is some visitors edit the tree and delete nodes, so this later debug message doesn't know that and may follow the bogus pointer.  So the warning is "real" in the sense that it might be an invalid pointer.

It's very rare that this info is needed for debug.  Perhaps it's best to comment out the offending lines with a comment as to why doing so, so they are there in case we need to debug an iterp problem at some point in the future.

Does that solve all your issues with ASAN?  We do runtime checks with the sanitizer but I don't think have verilator itself built that way in regressions.
