### ISSUE TITLE
Segmentation fault at AstNode::privateAs<AstNodeDType, AstNode*> (nodep=0x1) at ../V3Ast.h:2073

### ISSUE THREAD

**Issue by solomatnikov** [verilator/verilator#4281]
```
(gdb) run --prefix Vt_class_typedef ../obj_vlt/t_class_typedef/Vt_class_typedef__main.cpp --exe --make gmake --x-assign unique -cc -Mdir obj_vlt/t_class_typedef --fdedup --debug-check --comp-limit-members 10 --clk clk  -f input.vc +define+TEST_OBJ_DIR=obj_vlt/t_class_typedef +define+TEST_DUMPFILE=obj_vlt/t_class_typedef/simx.vcd t/t_class_typedef.v --debug --gdbbt
Starting program: .../verilator/bin/verilator_bin_dbg --prefix Vt_class_typedef ../obj_vlt/t_class_typedef/Vt_class_typedef__main.cpp --exe --make gmake --x-assign unique -cc -Mdir obj_vlt/t_class_typedef --fdedup --debug-check --comp-limit-members 10 --clk clk  -f input.vc +define+TEST_OBJ_DIR=obj_vlt/t_class_typedef +define+TEST_DUMPFILE=obj_vlt/t_class_typedef/simx.vcd t/t_class_typedef.v --debug --gdbbt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
AstNode::privateAs<AstNodeDType, AstNode*> (nodep=0x1) at ../V3Ast.h:2073
2073	        UASSERT_OBJ(!nodep || privateTypeTest<T>(nodep), nodep,
(gdb) bt
#0  AstNode::privateAs<AstNodeDType, AstNode*> (nodep=0x1) at ../V3Ast.h:2073
#1  0x00000000005428da in AstTypedef::childDTypep (this=0x14276c0) at ../V3Ast.h:1638
#2  AstTypedef::subDTypep (this=0x14276c0) at ../V3AstNodeOther.h:1566
#3  AstTypedef::dump (this=0x14276c0, str=...) at ../V3AstNodes.cpp:1764
#4  0x00000000005449b0 in AstRefDType::dump (this=0x1452a40, str=...) at ../V3AstNodes.cpp:1791
#5  0x000000000045bb00 in AstNode::v3errorEnd (this=this@entry=0x1452a40, str=...) at ../V3Ast.cpp:1331
#6  0x000000000045bcc1 in AstNode::v3errorEndFatal (this=this@entry=0x1452a40, str=...) at ../V3Ast.cpp:1293
#7  0x000000000057d028 in BrokenCheckVisitor::processEnter (this=this@entry=0x7fffffffc840, nodep=nodep@entry=0x1452a40) at ../V3Error.h:366
#8  0x000000000057d97f in BrokenCheckVisitor::processAndIterate (nodep=0x1452a40, this=0x7fffffffc840) at ../V3Broken.cpp:313
#9  BrokenCheckVisitor::visit (this=0x7fffffffc840, nodep=0x1452a40) at ../V3Broken.cpp:313
#10 0x000000000043c196 in VNVisitorConst::visit (this=<optimized out>, nodep=<optimized out>) at ./V3Ast__gen_visitor_defns.h:254
#11 0x000000000043c6ab in VNVisitorConst::visit (this=<optimized out>, nodep=<optimized out>) at ./V3Ast__gen_visitor_defns.h:328
#12 0x000000000054e8fe in AstRefDType::accept (this=<optimized out>, v=...) at ../V3AstNodeDType.h:1081
#13 0x0000000000457aeb in AstNode::iterateAndNextConst (this=<optimized out>, v=...) at ../V3Ast.cpp:1000
#14 0x0000000000457b6b in AstNode::iterateChildrenConst (this=this@entry=0x1452c20, v=...) at ../V3Ast.cpp:932
#15 0x0000000000580509 in VNVisitorConst::iterateChildrenConst (nodep=0x1452c20, this=0x7fffffffc840) at ../V3Ast.h:2522
#16 BrokenCheckVisitor::processAndIterate (nodep=0x1452c20, this=0x7fffffffc840) at ../V3Broken.cpp:202
#17 BrokenCheckVisitor::visit (this=0x7fffffffc840, nodep=0x1452c20) at ../V3Broken.cpp:305
#18 0x000000000054f626 in AstVar::accept (this=<optimized out>, v=...) at ../V3AstNodeOther.h:1777
#19 0x0000000000457aeb in AstNode::iterateAndNextConst (this=<optimized out>, v=...) at ../V3Ast.cpp:1000
#20 0x0000000000457b7c in AstNode::iterateChildrenConst (this=this@entry=0x14515d0, v=...) at ../V3Ast.cpp:933
#21 0x000000000057d98a in VNVisitorConst::iterateChildrenConst (nodep=0x14515d0, this=0x7fffffffc840) at ../V3Ast.h:2522
#22 BrokenCheckVisitor::processAndIterate (nodep=0x14515d0, this=0x7fffffffc840) at ../V3Broken.cpp:202
#23 BrokenCheckVisitor::visit (this=0x7fffffffc840, nodep=0x14515d0) at ../V3Broken.cpp:313
#24 0x000000000043c230 in VNVisitorConst::visit (this=<optimized out>, nodep=<optimized out>) at ./V3Ast__gen_visitor_defns.h:263
#25 0x000000000043bfa5 in VNVisitorConst::visit (this=<optimized out>, nodep=<optimized out>) at ./V3Ast__gen_visitor_defns.h:226
#26 0x000000000054f73c in AstModule::accept (this=<optimized out>, v=...) at ../V3AstNodeOther.h:2217
#27 0x0000000000457aeb in AstNode::iterateAndNextConst (this=<optimized out>, v=...) at ../V3Ast.cpp:1000
#28 0x0000000000457b6b in AstNode::iterateChildrenConst (this=this@entry=0x135d3a0, v=...) at ../V3Ast.cpp:932
#29 0x000000000057d98a in VNVisitorConst::iterateChildrenConst (nodep=0x135d3a0, this=0x7fffffffc840) at ../V3Ast.h:2522
#30 BrokenCheckVisitor::processAndIterate (nodep=0x135d3a0, this=0x7fffffffc840) at ../V3Broken.cpp:202
#31 BrokenCheckVisitor::visit (this=0x7fffffffc840, nodep=0x135d3a0) at ../V3Broken.cpp:313
#32 0x000000000043c09e in VNVisitorConst::visit (this=<optimized out>, nodep=<optimized out>) at ./V3Ast__gen_visitor_defns.h:240
#33 0x000000000054f4bc in AstNetlist::accept (this=<optimized out>, v=...) at ../V3AstNodeOther.h:1166
#34 0x0000000000579399 in VNVisitorConst::iterateConstNull (nodep=0x135d3a0, this=0x7fffffffc840) at ../V3Ast.h:2520
#35 BrokenCheckVisitor::BrokenCheckVisitor (nodep=0x135d3a0, this=0x7fffffffc840) at ../V3Broken.cpp:318
#36 V3Broken::brokenAll (nodep=nodep@entry=0x135d3a0) at ../V3Broken.cpp:348
#37 0x00000000004ebe82 in AstNode::dumpTreeFile (this=0x135d3a0, filename="obj_vlt/t_class_typedef/Vt_class_typedef_008_param.tree", append=append@entry=false, doDump=doDump@entry=false, doCheck=doCheck@entry=true) at ../V3Ast.cpp:1235
#38 0x000000000084b728 in V3Global::dumpCheckGlobalTree (stagename="param", newNumber=newNumber@entry=0, doDump=doDump@entry=false) at ../V3Global.h:131
#39 0x00000000009dfcde in V3Param::param (rootp=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:256
#40 0x0000000000407e11 in process () at ../V3Global.h:131
#41 0x000000000040ab4b in verilate (argString="--prefix Vt_class_typedef ../obj_vlt/t_class_typedef/Vt_class_typedef__main.cpp --exe --make gmake --x-assign unique -cc -Mdir obj_vlt/t_class_typedef --fdedup --debug-check --comp-limit-members 10 --"...) at ../Verilator.cpp:636
#42 0x000000000040c24b in main (argc=<optimized out>, argv=0x7fffffffd348) at ../Verilator.cpp:758
```

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

```
package param_pkg;

   localparam int AW=37;
   localparam int DW=256;
   localparam int MW=DW/8;

endpackage

package pkg;

class C #(parameter AW=param_pkg::AW);
  typedef enum logic [2:0] {
    PutF           = 3'h 0,
    Get            = 3'h 4
  } a_op_t;

  typedef enum logic [2:0] {
    AccessAck      = 3'h 0,
    AccessAckData  = 3'h 1
  } d_op_t;

  typedef struct packed {
    logic                        valid;
    a_op_t                       opcode;
    logic  [param_pkg::AW-1:0]   address;
    logic  [param_pkg::MW-1:0]   mask;
    logic  [param_pkg::DW-1:0]   data;
  } a_ch_t;

  typedef struct packed {
    logic                        valid;
    d_op_t                       opcode;
    logic  [param_pkg::AW-1:0]   address;
    logic  [param_pkg::MW-1:0]   mask;
    logic  [param_pkg::DW-1:0]   data;
  } d_ch_t;

endclass

endpackage

import param_pkg::*;
import pkg::*;

module adapter_mem
  #(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 32
    )
  (
   input                           clk,
   input                           reset_l,

   output logic                    a_ready,
   input  C::a_ch_t                a_channel,
   input  logic                    d_ready,
   output C::d_ch_t                d_channel,

   output logic [ADDR_WIDTH-1:0]   addr,
   output logic                    w_en,
   output logic [DATA_WIDTH-1:0]   w_data,
   output logic [DATA_WIDTH/8-1:0] w_mask,
   output logic                    r_en,
   input  logic [DATA_WIDTH-1:0]   r_data
   );

   logic                  a_fire = a_ready && a_channel.valid;
   logic 		  a_read = a_channel.opcode == C#()::Get;
   logic 		  r_full;
   logic 		  r_read;
   logic 		  r_en_reg;
   logic [DATA_WIDTH-1:0] r_data_reg;

   assign addr   = a_channel.address;
   assign w_en   = a_fire && !a_read;
   assign w_mask = a_channel.mask;
   assign w_data = a_channel.data;
   assign r_en   = a_fire && a_read;

   assign a_ready = ~r_full | d_ready;

   assign d_channel.valid  = r_full;
   assign d_channel.opcode = r_read ? C::d_op_t'(C#()::AccessAckData) : C::d_op_t'(C#()::AccessAck);
   assign d_channel.data   = r_en_reg ? r_data : r_data_reg;

   always_ff @(posedge clk) begin
      if (a_fire) begin
	 r_read   <= a_read;
      end
      r_en_reg <= r_en;
      if (r_en_reg) begin
	 r_data_reg <= r_data;
      end
   end

   always @(posedge clk or negedge reset_l) begin
      if (!reset_l) begin
	 r_full <= 1'h0;
      end else begin
	 r_full <= a_fire ||
		   (d_ready ? 1'h0 : r_full);
      end
   end

endmodule

module testmem #(
   parameter DATA_WIDTH=64,
   parameter ADDR_WIDTH=32
) (
   input logic 			  clk,
   input logic [ADDR_WIDTH-1:0]   addr,
   input logic 			  w_en,
   input logic [DATA_WIDTH-1:0]   w_data,
   input logic [DATA_WIDTH/8-1:0] w_mask,
   input logic 			  r_en,
   output logic [DATA_WIDTH-1:0]  r_data
   );

   logic [DATA_WIDTH-1:0] mem [logic [ADDR_WIDTH-1:0]];
   logic [ADDR_WIDTH-1:0] addr_reg;

   always @(posedge clk)
     if (r_en) addr_reg <= addr;

   assign r_data = mem[addr_reg];

   generate
      genvar i;
      for (i = 0; i < DATA_WIDTH/8; i = i + 1)
	always @(posedge clk)
	  if (w_en && w_mask[i])
	    mem[addr][i*8+7:i*8] <= w_data[i*8+7:i*8];
   endgenerate

endmodule // testmem

module t (/*AUTOARG*/
   // Inputs
   clk, reset_l
   );

   input     clk;
   input     reset_l;

   logic     a_ready;
   C::a_ch_t a_channel;
   logic     d_ready;
   C::d_ch_t d_channel;

   logic [AW-1:0]   addr;
   logic 	    w_en;
   logic [DW-1:0]   w_data;
   logic [DW/8-1:0] w_mask;
   logic 	    r_en;
   logic [DW-1:0]   r_data;

   adapter_mem #(.DATA_WIDTH(DW), .ADDR_WIDTH(AW)) adapter_mem( .* );

   testmem #(.DATA_WIDTH(DW), .ADDR_WIDTH(AW)) testmem( .* );

   initial begin
      if ($bits(a_channel.address) != AW) $stop;
      if ($bits(a_channel.data) != DW) $stop;

      a_channel.valid = 1'b0;
  end

   always @ (posedge clk) begin
      if (reset_l) begin
	 a_channel.valid   = 1'b1;
	 a_channel.opcode  = C#()::Put;
	 a_channel.address = 16;

	 $write("*-* All Finished *-*\n");
	 $finish;
      end
   end

endmodule
```

What 'verilator --version' are you using?  Did you try it with the git master version?
```
Verilator 5.011 devel rev v5.010-113-g6cb0335d2
```
What OS and distribution are you using?
```
Linux loran 4.18.0-492.el8.x86_64 #1 SMP Tue May 9 17:56:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
May we assist you in trying to fix this in Verilator yourself?

**Not sure**

**Comment by wsnyder** [comment]
Confirmed, needs more debug, the 0x1 indicates that what is being pointed to got deleted (so it's a dangling pointer).  A pull request to fix this would be appreciated.
