### ISSUE TITLE
Tests: clang_check_attributes failures on Ubuntu24.10

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#5619]
@b-chmiel, might you be able to look into these two failures related to clang_check_attributes when running on Ubuntu 24.10?

```
test_regress/t/t_dist_lint_py.py

    ************* Module clang_check_attributes
    nodist/clang_check_attributes:41:4: E0244: Extending inherited Enum class "CursorKind" (invalid-enum-\
extension)


test_regress/t/t_a5_attributes_src.py

    Traceback (most recent call last):
      File "/root/verilator/test_regress/../nodist/clang_check_attributes", line 1183, in <module>
        main()
      File "/root/verilator/test_regress/../nodist/clang_check_attributes", line 1151, in main
        entry_list = list(entry)
                     ^^^^^^^^^^^
    TypeError: 'NoneType' object is not iterable
``

**Comment by b-chmiel** [comment]
I created a PR with a fix. Both errors doesn't seem harmful, but I'd added a warning to catch the situation when an entry for a file is missing from compilation database.
